/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Userdashboard;

import admin.AccountAdmin;
import admin.LogInForm;
import config.Session;
import config.dbConnector;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;

/**
 *
 * @author admin
 */
public class GenPin extends javax.swing.JFrame {
private boolean isPinCreationOpen = false;
    
    public GenPin() {
         setUndecorated(true);
         addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                
            }
        });
        addMouseMotionListener(new java.awt.event.MouseAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                
            }
        });
        initComponents();
        setUpPinFields();
    }

  private void setUpPinFields() {
        JTextField[] pinFields = {s1, s2, s3, s4, s5, s6};

        for (int i = 0; i < pinFields.length; i++) {
            
            ((AbstractDocument) pinFields[i].getDocument()).setDocumentFilter(new OneCharFilter());

            
            final int index = i;
            pinFields[i].addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    if (evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_TAB) {
                        if (index < pinFields.length - 1) {
                            pinFields[index + 1].requestFocus();
                        }
                    }
                }
            });
        }
  }
  private class OneCharFilter extends DocumentFilter {
        public void insertString(DocumentFilter.FilterBypass fb, int offset, String string, AttributeSet attr) throws BadLocationException {
            if (string != null && string.length() > 0) {
                if (string.length() > 1) {
                    string = string.substring(0, 1); 
                }
                super.insertString(fb, offset, string, attr);
            }
        }

        public void replace(DocumentFilter.FilterBypass fb, int offset, int length, String text, AttributeSet attrs) throws BadLocationException {
            if (text != null && text.length() > 0) {
                if (text.length() > 1) {
                    text = text.substring(0, 1); 
                }
                super.replace(fb, offset, length, text, attrs);
            }
        }

        @Override
        public void remove(DocumentFilter.FilterBypass fb, int offset, int length) throws BadLocationException {
            super.remove(fb, offset, length);
        }
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        po = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        sq = new javax.swing.JLabel();
        con = new javax.swing.JButton();
        s6 = new javax.swing.JTextField();
        s1 = new javax.swing.JTextField();
        s2 = new javax.swing.JTextField();
        s3 = new javax.swing.JTextField();
        s4 = new javax.swing.JTextField();
        s5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(240, 245, 179));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(114, 240, 194));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Cooper Black", 0, 36)); // NOI18N
        jLabel2.setText("Recovery Mode");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 320, 116));

        jButton2.setText("LOGIN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 40, 180, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 120));

        po.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictires/gwapo.gif"))); // NOI18N
        jPanel1.add(po, new org.netbeans.lib.awtextra.AbsoluteConstraints(-240, 460, 820, 240));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sq.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        sq.setText("Security Question!");
        jPanel2.add(sq, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 180, 77));

        con.setText("CONTINUE");
        con.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conActionPerformed(evt);
            }
        });
        jPanel2.add(con, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 140, 40));
        jPanel2.add(s6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 70, 60));
        jPanel2.add(s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 70, 60));
        jPanel2.add(s2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 70, 60));
        jPanel2.add(s3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 70, 60));
        jPanel2.add(s4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 70, 60));
        jPanel2.add(s5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 70, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 640, 280));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel1.setText("Create Pin!");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 985, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
           int confirm = javax.swing.JOptionPane.showConfirmDialog(
            this, "Are you sure you wanna discard this recovery process?", "Confirmation",
            javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            this.dispose();

            AccountAdmin loginPage = new AccountAdmin();
            loginPage.setVisible(true);
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void conActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conActionPerformed
       String pin = s1.getText() + 
                 s2.getText() + 
                 s3.getText() + 
                 s4.getText() + 
                 s5.getText() + 
                 s6.getText();

    if (pin.length() != 6 || !pin.matches("\\d{6}")) {
        JOptionPane.showMessageDialog(
            null,
            "Please enter a valid 6-digit PIN. It should contain only numbers.",
            "Error",
            JOptionPane.ERROR_MESSAGE
        );
        return; 
    }

    String username = Session.getInstance().getU_username(); 
    String sql = "UPDATE users SET PIN = '" + pin + "' WHERE u_username = '" + username + "'";

    dbConnector dbConnect = new dbConnector();
      int rowsAffected = dbConnect.insertData(sql);
    boolean success = rowsAffected > 0;

    if (success) {
        Session.getInstance().setPIN(pin); 
        JOptionPane.showMessageDialog(null, "PIN created successfully!");
        AccountAdmin AA = new AccountAdmin();
        AA.setVisible(true);
        this.dispose();
    } else {
        JOptionPane.showMessageDialog(
            null,
            "Error saving PIN to database.",
            "Database Error",
            JOptionPane.ERROR_MESSAGE
        );
    }  
    }//GEN-LAST:event_conActionPerformed

 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenPin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenPin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenPin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenPin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenPin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton con;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel po;
    private javax.swing.JTextField s1;
    private javax.swing.JTextField s2;
    private javax.swing.JTextField s3;
    private javax.swing.JTextField s4;
    private javax.swing.JTextField s5;
    private javax.swing.JTextField s6;
    private javax.swing.JLabel sq;
    // End of variables declaration//GEN-END:variables

    }
