/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Userdashboard;

import admin.AccountAdmin;
import config.Session;
import config.dbConnector;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class GenQue extends javax.swing.JFrame {
    public static String userType;

    /**
     * Creates new form GenQue
     */
    public GenQue() {
         setUndecorated(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        po = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        sq = new javax.swing.JLabel();
        con = new javax.swing.JButton();
        s6 = new javax.swing.JTextField();
        s5 = new javax.swing.JTextField();
        sq1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(240, 245, 179));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(114, 240, 194));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Cooper Black", 0, 36)); // NOI18N
        jLabel2.setText("Recovery Mode");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 320, 116));

        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 40, 180, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 120));

        po.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictires/gwapo.gif"))); // NOI18N
        jPanel1.add(po, new org.netbeans.lib.awtextra.AbsoluteConstraints(-240, 460, 820, 240));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sq.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        sq.setText("Answer:");
        jPanel2.add(sq, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 180, 77));

        con.setText("CONTINUE");
        con.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conActionPerformed(evt);
            }
        });
        jPanel2.add(con, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 140, 40));

        s6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s6ActionPerformed(evt);
            }
        });
        jPanel2.add(s6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 460, 60));

        s5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s5ActionPerformed(evt);
            }
        });
        jPanel2.add(s5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 460, 60));

        sq1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        sq1.setText("Question:");
        jPanel2.add(sq1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 180, 77));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 780, 360));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel1.setText("Create Question!");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, 70));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictires/nenpo.png"))); // NOI18N
        jLabel10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel10KeyPressed(evt);
            }
        });
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 1000, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 985, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            int confirm = javax.swing.JOptionPane.showConfirmDialog(
        this, "Are you sure you want to discard this recovery process?", "Confirmation",
        javax.swing.JOptionPane.YES_NO_OPTION);

    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
        this.dispose();

        // Get the user type directly from the static variable
        String userType = GenQue.userType;

        if ("admin".equalsIgnoreCase(userType)) {
            AccountAdmin loginPage = new AccountAdmin();
            loginPage.setVisible(true);
        } else if ("customer".equalsIgnoreCase(userType)) {
            userAccounts userPage = new userAccounts();
            userPage.setVisible(true);
        } else {
            // Handle unexpected user type if necessary
            JOptionPane.showMessageDialog(this, "Unknown user type.");
        }
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void conActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conActionPerformed
       String squestion = s5.getText().trim();
    String answer = s6.getText().trim(); 

    System.out.println("Question: '" + squestion + "' (Length: " + squestion.length() + ")");
    
    if (squestion.isEmpty() || answer.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Question and Answer can't be empty. Please fill out the form.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (squestion.length() < 5) {
        JOptionPane.showMessageDialog(this, "Invalid Question! It must be at least 5 characters long.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (!squestion.endsWith("?")) {
        JOptionPane.showMessageDialog(this, "Invalid Question! It must end with a question mark.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    String username = Session.getInstance().getU_username(); 
    String sql = "UPDATE users SET SecurityQuestion = '" + squestion + "', answer = '" + answer + "' WHERE u_username = '" + username + "'";

    dbConnector dbConnect = new dbConnector();
    
    try {
        int rowsAffected = dbConnect.insertData(sql);

        if (rowsAffected > 0) {
            Session.getInstance().setSecurityQuestion(squestion); 
            Session.getInstance().setAnswer(answer);
            JOptionPane.showMessageDialog(this, "Security Question created successfully!");

            // Add confirmation dialog and user type handling
            int confirm = javax.swing.JOptionPane.showConfirmDialog(
                this, "Do you want to go back to the previous page?", "Confirmation",
                javax.swing.JOptionPane.YES_NO_OPTION);

            if (confirm == javax.swing.JOptionPane.YES_OPTION) {
                this.dispose();

                // Get the user type directly from the static variable
                String userType = GenQue.userType;

                if ("admin".equalsIgnoreCase(userType)) {
                    AccountAdmin aa = new AccountAdmin();
                    aa.setVisible(true);
                } else if ("customer".equalsIgnoreCase(userType)) {
                    userAccounts userPage = new userAccounts();
                    userPage.setVisible(true);
                } else {
                    // Handle unexpected user type if necessary
                    JOptionPane.showMessageDialog(this, "Unknown user type.");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Error saving Security Question to database.", "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "An unexpected error occurred: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace(); 
    }
    }//GEN-LAST:event_conActionPerformed

    private void s6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s6ActionPerformed
       String answer = s6.getText().trim();

        if (answer.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Answer cannot be empty!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_s6ActionPerformed

    private void s5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s5ActionPerformed
        String squestion = s5.getText().trim();

        if (squestion.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Security Question cannot be empty!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        else if (squestion.length() < 5 || !squestion.matches(".*[?]$")) {
            JOptionPane.showMessageDialog(this, "Invalid Question! It must be at least 5 characters long and end with a question mark.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_s5ActionPerformed

    private void jLabel10KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel10KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenQue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenQue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenQue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenQue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenQue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton con;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel po;
    private javax.swing.JTextField s5;
    private javax.swing.JTextField s6;
    private javax.swing.JLabel sq;
    private javax.swing.JLabel sq1;
    // End of variables declaration//GEN-END:variables
}
