/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Userdashboard;

import admin.LogInForm;
import config.Session;
import config.dbConnector;
import java.awt.Color;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import java.text.ParseException;
import java.util.Date;
import config.TimeConflick;


/**
 *
 * @author admin
 */
public class userdashboard extends javax.swing.JFrame {

    public userdashboard() {
        initComponents();
         pet.setText("Pet Name");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lg = new javax.swing.JLabel();
        acc = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        ya = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        date = new com.toedter.calendar.JCalendar();
        type = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sumbit = new javax.swing.JButton();
        pet = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        time = new com.raven.swing.TimePicker();
        jLabel8 = new javax.swing.JLabel();
        tar = new javax.swing.JTextField();
        shit = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(240, 245, 179));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(114, 240, 194));

        jLabel2.setFont(new java.awt.Font("Cooper Black", 0, 36)); // NOI18N
        jLabel2.setText("Set Appointment!");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addContainerGap(716, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 120));

        jButton3.setText("Log In");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 760, 80, 30));

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lg.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lg.setText("Logout");
        lg.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        lg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lgMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lgMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lgMouseExited(evt);
            }
        });
        jPanel2.add(lg, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 120, 40));

        acc.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        acc.setText("Account");
        acc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        acc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                accMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                accMouseExited(evt);
            }
        });
        jPanel2.add(acc, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 100, 40));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        ya.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ya.setText("Your Appointments");
        ya.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51)));
        ya.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                yaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                yaMouseExited(evt);
            }
        });
        jPanel2.add(ya, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 160, 40));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel12.setText("Set Appointment");
        jLabel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, null, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 160, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictires/unnamed (1).png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictires/unnamed (2).png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 40, 50));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel13.setText("Dashboard");
        jLabel13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 100, 40));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictires/unnamed (3).png"))); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictires/unnamed (1).png"))); // NOI18N
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 220, 580));

        date.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, 420, 240));

        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Croptop", "Lion Cut", "Mohowk", "Top Knot", "Mushroom", "Edgar Cut", "Flat Top", "Teddy Bear Cut", " " }));
        type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeActionPerformed(evt);
            }
        });
        jPanel1.add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 260, 50));

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel4.setText("Select Time:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 260, 30));

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel6.setText("Select Date to Appoint:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, 260, 30));

        sumbit.setText("SUBMIT");
        sumbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumbitActionPerformed(evt);
            }
        });
        jPanel1.add(sumbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 610, 160, 30));

        pet.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                petFocusGained(evt);
            }
        });
        jPanel1.add(pet, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 260, 50));

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel7.setText("Cost:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 260, 30));

        time.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        jPanel1.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 260, 290));

        jLabel8.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel8.setText("Enter Pet Name:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 260, 30));

        tar.setText("Duration");
        tar.setEnabled(false);
        jPanel1.add(tar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, 260, 50));

        shit.setText("Cost");
        shit.setEnabled(false);
        jPanel1.add(shit, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, 260, 50));

        jLabel9.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel9.setText("Select Haircut:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 260, 30));

        jLabel10.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel10.setText("Possible Duration:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 260, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 985, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void accMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accMouseClicked
        userAccounts uc = new userAccounts();
        uc.setVisible(true);
        this.dispose();


        // TODO add your handling code here:
    }//GEN-LAST:event_accMouseClicked

    private void yaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yaMouseClicked
        userAppointment ua = new userAppointment();
        ua.setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_yaMouseClicked

    private void lgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgMouseClicked
       int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "Confirm Logout", JOptionPane.YES_NO_OPTION);
    
    if (confirm == JOptionPane.YES_OPTION) {
        JOptionPane.showMessageDialog(this, "You have successfully logged out!", "Logout", JOptionPane.INFORMATION_MESSAGE);
        
        LogInForm li = new LogInForm();
        li.setVisible(true);
        
        this.dispose();
    }
    }//GEN-LAST:event_lgMouseClicked

    private void yaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yaMouseEntered
      ya.setForeground(new java.awt.Color(114,240,194));
    }//GEN-LAST:event_yaMouseEntered

    private void yaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yaMouseExited
    ya.setForeground(Color.BLACK);    }//GEN-LAST:event_yaMouseExited

    private void accMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accMouseEntered
    acc.setForeground(new java.awt.Color(114,240,194));    }//GEN-LAST:event_accMouseEntered

    private void accMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accMouseExited
    acc.setForeground(Color.BLACK);    }//GEN-LAST:event_accMouseExited

    private void lgMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgMouseEntered
      lg.setForeground(new java.awt.Color(114,240,194));

    }//GEN-LAST:event_lgMouseEntered

    private void lgMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgMouseExited
       lg.setForeground(Color.BLACK);
    }//GEN-LAST:event_lgMouseExited

    private void sumbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumbitActionPerformed
 config.TimeConflick timeHelper = new config.TimeConflick(); // only declared once

    java.util.Date selectedDateUtil = date.getDate();
    String selectedDate = new SimpleDateFormat("yyyy-MM-dd").format(selectedDateUtil);

    String petName = pet.getText().trim();
    String selectedHaircut = (String) type.getSelectedItem();
    String selectedTime = time.getSelectedTime();

    String formattedTime = "";
    try {
        SimpleDateFormat inputFormat = new SimpleDateFormat("hh:mm a");
        SimpleDateFormat outputFormat = new SimpleDateFormat("HH:mm:ss");
        Date dateTime = inputFormat.parse(selectedTime);
        formattedTime = outputFormat.format(dateTime);
    } catch (ParseException e) {
        JOptionPane.showMessageDialog(this, "Invalid time format!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (petName.isEmpty() || selectedDate.isEmpty() || selectedHaircut == null || formattedTime.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill in all fields!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    java.util.Date currentDate = new java.util.Date();
    if (selectedDateUtil.before(currentDate)) {
        JOptionPane.showMessageDialog(this, "The selected date and time must be in the future!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    int currentUserId = Session.getInstance().getId();
    String userFirstName = Session.getInstance().getU_fname();
    String userLastName = Session.getInstance().getU_lname();
    String userEmail = Session.getInstance().getU_email();
    String userContact = Session.getInstance().getCont(); // Retrieve contact number from Session

    // SQL query with 'groom' and 'haircut_id' columns
    String sql = "INSERT INTO appointments (date, time, pet_name, groom, haircut_id, cost, user_id, u_fname, u_lname, u_email, cont) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

try (Connection conn = new dbConnector().getConnection();
     PreparedStatement pst = conn.prepareStatement(sql)) {

    int haircutId = timeHelper.getHaircutId(selectedHaircut, conn);
    int haircutDuration = timeHelper.getHaircutDuration(haircutId, conn);
    BigDecimal haircutCost = timeHelper.getHaircutCost(selectedHaircut, conn);

    // ✅ Wrap the time conflict check in its own try-catch or expand this one
    try {
        if (!timeHelper.isTimeSlotAvailable(conn, selectedDate, formattedTime, haircutDuration)) {
            JOptionPane.showMessageDialog(this, "The selected time overlaps with another appointment!", "Time Conflict", JOptionPane.ERROR_MESSAGE);
            return;
        }
    } catch (ParseException pe) {
        JOptionPane.showMessageDialog(this, "Error parsing appointment time: " + pe.getMessage(), "Parse Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    pst.setString(1, selectedDate);
    pst.setString(2, formattedTime);
    pst.setString(3, petName);
    pst.setString(4, selectedHaircut);
    pst.setInt(5, haircutId);
    pst.setBigDecimal(6, haircutCost);
    pst.setInt(7, currentUserId);
    pst.setString(8, userFirstName);
    pst.setString(9, userLastName);
    pst.setString(10, userEmail);
    pst.setString(11, userContact);

    int rowsAffected = pst.executeUpdate();
    if (rowsAffected > 0) {
        JOptionPane.showMessageDialog(this, "Appointment submitted successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    }

} catch (SQLException ex) {
    JOptionPane.showMessageDialog(this, "Database Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }    }//GEN-LAST:event_sumbitActionPerformed

    private void typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeActionPerformed
    TimeConflick timeHelper = new TimeConflick();
    String selectedHaircut = (String) type.getSelectedItem();  
    try (Connection conn = new dbConnector().getConnection()) {
        
        int haircutId = timeHelper.getHaircutId(selectedHaircut, conn);
        
        BigDecimal cost = timeHelper.getHaircutCost(selectedHaircut, conn);
        
        int duration = timeHelper.getHaircutDuration(haircutId, conn);
        shit.setText(cost.toString());
        tar.setText(duration + " minutes");
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error retrieving haircut details: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_typeActionPerformed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        NewDashboard ndb = new NewDashboard();
        ndb.setVisible(true);
        this.dispose();

       
    }//GEN-LAST:event_jLabel13MouseClicked

    private void petFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_petFocusGained
      pet.setText("");
    }//GEN-LAST:event_petFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userdashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userdashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userdashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userdashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userdashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acc;
    private com.toedter.calendar.JCalendar date;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lg;
    private javax.swing.JTextField pet;
    public javax.swing.JTextField shit;
    private javax.swing.JButton sumbit;
    private javax.swing.JTextField tar;
    private com.raven.swing.TimePicker time;
    private javax.swing.JComboBox<String> type;
    private javax.swing.JLabel ya;
    // End of variables declaration//GEN-END:variables
}
